<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>10</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\IoTMonitoringSystem.Domain\IoTMonitoringSystem.Domain.csproj" />
      <ProjectReference Include="..\IoTMonitoringSystem.Repository\IoTMonitoringSystem.Repository.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
    </ItemGroup>

</Project>
